export const GET_CLASSES_LOAD="GET_CLASSES_LOAD";
export const GET_CLASSES_SUCCESS="GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILED="GET_CLASSES_FAILED";
export const DELETE_CLASSE = "DELETE_CLASSE"; 
export const EDIT_CLASSE="EDIT_CLASSE";
